# Generated by Django 4.2.5 on 2023-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='drinks',
            field=models.ManyToManyField(blank=True, choices=[('Bier', 'Bier'), ('Sekt', 'Sekt'), ('Wein', 'Wein'), ('Aperol', 'Aperol'), ('Limo', 'Limo'), ('Cola', 'Cola')], to='rsvp.drink', verbose_name='Getränke'),
        ),
    ]
