# Generated by Django 4.2.5 on 2023-10-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_drink_guest_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='drinks',
        ),
    ]
