# Generated by Django 4.2.5 on 2023-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_remove_drink_drinks_guest_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='rsvp.drink', verbose_name='Getränke'),
        ),
    ]
