# Generated by Django 4.2.5 on 2023-10-15 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_alter_guest_drinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='rsvp_date',
        ),
        migrations.AddField(
            model_name='guest',
            name='participation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
