# Generated by Django 4.2.5 on 2023-10-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0008_remove_guest_participation_timestamp_guest_rsvp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
