# Generated by Django 4.2.5 on 2023-10-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_alter_guest_rsvp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guests',
        ),
    ]
